-- Quality system: deviations, CAPA and change control.
--
-- The thread an inspector pulls: something went wrong, it was investigated, an
-- action was taken, and somebody checked the action worked. Generated by
-- prisma migrate diff against the committed migration history.

-- CreateEnum
CREATE TYPE "DeviationCategory" AS ENUM ('PROCESS', 'EQUIPMENT', 'DOCUMENTATION', 'UTILITY', 'MATERIAL', 'PERSONNEL', 'ENVIRONMENTAL', 'OTHER');

-- CreateEnum
CREATE TYPE "DeviationSeverity" AS ENUM ('UNCLASSIFIED', 'MINOR', 'MAJOR', 'CRITICAL');

-- CreateEnum
CREATE TYPE "DeviationStatus" AS ENUM ('OPEN', 'UNDER_INVESTIGATION', 'PENDING_APPROVAL', 'CLOSED', 'CANCELLED');

-- CreateEnum
CREATE TYPE "ProductImpact" AS ENUM ('NOT_ASSESSED', 'NONE', 'POTENTIAL', 'CONFIRMED');

-- CreateEnum
CREATE TYPE "CapaKind" AS ENUM ('CORRECTION', 'CORRECTIVE', 'PREVENTIVE');

-- CreateEnum
CREATE TYPE "CapaStatus" AS ENUM ('OPEN', 'IN_PROGRESS', 'COMPLETED', 'VERIFIED', 'CANCELLED');

-- CreateEnum
CREATE TYPE "EffectivenessVerdict" AS ENUM ('EFFECTIVE', 'NOT_EFFECTIVE', 'TOO_EARLY_TO_TELL');

-- CreateEnum
CREATE TYPE "ChangeType" AS ENUM ('SPECIFICATION', 'METHOD', 'EQUIPMENT', 'PROCESS', 'DOCUMENT', 'SUPPLIER', 'SYSTEM', 'OTHER');

-- CreateEnum
CREATE TYPE "ChangeClassification" AS ENUM ('UNCLASSIFIED', 'MINOR', 'MAJOR', 'CRITICAL');

-- CreateEnum
CREATE TYPE "ChangeStatus" AS ENUM ('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'IMPLEMENTED', 'CLOSED', 'REJECTED', 'CANCELLED');

-- CreateTable
CREATE TABLE "deviation" (
    "id" UUID NOT NULL,
    "tenantId" UUID NOT NULL,
    "deviationNumber" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "category" "DeviationCategory" NOT NULL,
    "severity" "DeviationSeverity" NOT NULL DEFAULT 'UNCLASSIFIED',
    "status" "DeviationStatus" NOT NULL DEFAULT 'OPEN',
    "batchId" UUID,
    "deviceId" UUID,
    "labId" UUID,
    "occurredAt" TIMESTAMP(3) NOT NULL,
    "detectedAt" TIMESTAMP(3) NOT NULL,
    "reportedBy" UUID NOT NULL,
    "reportedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "investigation" TEXT,
    "rootCause" TEXT,
    "impactAssessment" TEXT,
    "productImpact" "ProductImpact" NOT NULL DEFAULT 'NOT_ASSESSED',
    "closedBy" UUID,
    "closedAt" TIMESTAMP(3),

    CONSTRAINT "deviation_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "capa_action" (
    "id" UUID NOT NULL,
    "tenantId" UUID NOT NULL,
    "capaNumber" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "kind" "CapaKind" NOT NULL,
    "status" "CapaStatus" NOT NULL DEFAULT 'OPEN',
    "deviationId" UUID,
    "oosId" UUID,
    "changeControlId" UUID,
    "ownerId" UUID NOT NULL,
    "dueAt" TIMESTAMP(3) NOT NULL,
    "completedBy" UUID,
    "completedAt" TIMESTAMP(3),
    "completionNote" TEXT,
    "effectivenessDueAt" TIMESTAMP(3),
    "effectivenessCheckedBy" UUID,
    "effectivenessCheckedAt" TIMESTAMP(3),
    "effectivenessVerdict" "EffectivenessVerdict",
    "effectivenessNote" TEXT,
    "createdBy" UUID NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "capa_action_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "change_control" (
    "id" UUID NOT NULL,
    "tenantId" UUID NOT NULL,
    "changeNumber" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "changeType" "ChangeType" NOT NULL,
    "classification" "ChangeClassification" NOT NULL DEFAULT 'UNCLASSIFIED',
    "status" "ChangeStatus" NOT NULL DEFAULT 'DRAFT',
    "justification" TEXT NOT NULL,
    "impactAssessment" TEXT,
    "prerequisites" TEXT,
    "requestedBy" UUID NOT NULL,
    "requestedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "approvedBy" UUID,
    "approvedAt" TIMESTAMP(3),
    "approvalNote" TEXT,
    "implementedBy" UUID,
    "implementedAt" TIMESTAMP(3),
    "implementationNote" TEXT,
    "reviewedBy" UUID,
    "reviewedAt" TIMESTAMP(3),
    "reviewNote" TEXT,
    "rejectedReason" TEXT,

    CONSTRAINT "change_control_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "deviation_tenantId_status_occurredAt_idx" ON "deviation"("tenantId", "status", "occurredAt");

-- CreateIndex
CREATE INDEX "deviation_tenantId_batchId_idx" ON "deviation"("tenantId", "batchId");

-- CreateIndex
CREATE UNIQUE INDEX "deviation_tenantId_deviationNumber_key" ON "deviation"("tenantId", "deviationNumber");

-- CreateIndex
CREATE INDEX "capa_action_tenantId_status_dueAt_idx" ON "capa_action"("tenantId", "status", "dueAt");

-- CreateIndex
CREATE INDEX "capa_action_tenantId_deviationId_idx" ON "capa_action"("tenantId", "deviationId");

-- CreateIndex
CREATE UNIQUE INDEX "capa_action_tenantId_capaNumber_key" ON "capa_action"("tenantId", "capaNumber");

-- CreateIndex
CREATE INDEX "change_control_tenantId_status_requestedAt_idx" ON "change_control"("tenantId", "status", "requestedAt");

-- CreateIndex
CREATE UNIQUE INDEX "change_control_tenantId_changeNumber_key" ON "change_control"("tenantId", "changeNumber");

-- AddForeignKey
ALTER TABLE "deviation" ADD CONSTRAINT "deviation_batchId_fkey" FOREIGN KEY ("batchId") REFERENCES "material_batch"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "deviation" ADD CONSTRAINT "deviation_deviceId_fkey" FOREIGN KEY ("deviceId") REFERENCES "device"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "capa_action" ADD CONSTRAINT "capa_action_deviationId_fkey" FOREIGN KEY ("deviationId") REFERENCES "deviation"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "capa_action" ADD CONSTRAINT "capa_action_changeControlId_fkey" FOREIGN KEY ("changeControlId") REFERENCES "change_control"("id") ON DELETE SET NULL ON UPDATE CASCADE;

